# Generated by Django 3.0.11 on 2020-11-19 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gmail',
            field=models.EmailField(blank=True, help_text='GMail address, used for authentication.', max_length=200, verbose_name='GMail address'),
        ),
    ]
