# Generated by Django 3.0.11 on 2020-11-19 22:03

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_gmail'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, verbose_name='TaiChi biography.'),
        ),
        migrations.AddField(
            model_name='user',
            name='cell',
            field=phone_field.models.PhoneField(blank=True, help_text='Number used for text notifications', max_length=31, verbose_name='cell phone'),
        ),
        migrations.AddField(
            model_name='user',
            name='leaderFlag',
            field=models.BooleanField(default=False, verbose_name='User is a leader'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, max_length=31, verbose_name='home phone.'),
        ),
    ]
