# Generated by Django 3.0.11 on 2020-12-12 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20201205_1316'),
        ('users', '0003_auto_20201119_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='home_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.Location'),
        ),
    ]
