# Generated by Django 3.0.11 on 2020-12-12 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_home_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='home_address',
        ),
    ]
