# Generated by Django 3.0.11 on 2020-12-12 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_home_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sponsor',
            field=models.ForeignKey(help_text='User who applied leader designation.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
