# Generated by Django 3.0.11 on 2020-12-22 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_sponsor'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, help_text='Preferred city for TaiChi meetings.', max_length=30, null=True, verbose_name='City of residence.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sponsor',
            field=models.ForeignKey(help_text='User who applied leader designation.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
