# Generated by Django 3.0.11 on 2020-12-31 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
        ('users', '0008_user_favorite_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='resources',
            field=models.ManyToManyField(to='resources.Resource'),
        ),
    ]
