# Generated by Django 3.0.11 on 2021-02-12 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_resources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sponsor',
            field=models.ForeignKey(blank=True, help_text='User who applied leader designation.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
