# Generated by Django 3.2.7 on 2021-09-29 19:49

import dfwtaichi.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210225_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='biophoto',
            field=models.ImageField(blank=True, default='', upload_to=dfwtaichi.users.models.profile_pic_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
