# Generated by Django 3.0.11 on 2020-12-25 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('styles', '0003_auto_20201221_1222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting',
            options={'verbose_name': 'meeting', 'verbose_name_plural': 'meetings'},
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'verbose_name': 'series', 'verbose_name_plural': 'series'},
        ),
    ]
