# Generated by Django 3.0.11 on 2020-12-27 21:51

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('styles', '0004_auto_20201225_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text="Enter single word or 'quoted strings' to be used to find your series.", through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags to be searched to find your series'),
        ),
    ]
