# Generated by Django 3.0.11 on 2020-12-31 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
        ('styles', '0005_series_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='resources',
            field=models.ManyToManyField(to='resources.Resource'),
        ),
        migrations.AddField(
            model_name='style',
            name='resources',
            field=models.ManyToManyField(to='resources.Resource'),
        ),
    ]
