# Generated by Django 3.0.11 on 2021-07-17 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
        ('styles', '0006_auto_20201231_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='day',
            field=models.DateField(blank=True, verbose_name='Date of meeting'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='length',
            field=models.IntegerField(blank=True, verbose_name='Minutes that the meeting lasts'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='start',
            field=models.TimeField(blank=True, verbose_name='Start time of the meeting'),
        ),
        migrations.AlterField(
            model_name='style',
            name='resources',
            field=models.ManyToManyField(blank=True, to='resources.Resource'),
        ),
    ]
