# Generated by Django 3.2.7 on 2021-10-06 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('styles', '0007_auto_20210717_1621'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting',
            options={'get_latest_by': 'day', 'ordering': ['-day'], 'verbose_name': 'meeting', 'verbose_name_plural': 'meetings'},
        ),
        migrations.AlterModelOptions(
            name='meetingattendees',
            options={'verbose_name': 'attendee', 'verbose_name_plural': 'attendees'},
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'ordering': ['-visibility'], 'verbose_name': 'series', 'verbose_name_plural': 'series'},
        ),
        migrations.AlterModelOptions(
            name='seriesleaders',
            options={'ordering': ['primary'], 'verbose_name': 'leader', 'verbose_name_plural': 'leaders'},
        ),
        migrations.AlterModelOptions(
            name='seriesmembers',
            options={'ordering': ['active'], 'verbose_name': 'member', 'verbose_name_plural': 'members'},
        ),
        migrations.AlterField(
            model_name='meeting',
            name='day',
            field=models.DateField(blank=True, verbose_name='Date of last meeting'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='meetingattendees',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='series',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='seriesleaders',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='seriesmembers',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='seriesmembers',
            name='last_meeting',
            field=models.DateField(blank=True, null=True, verbose_name='Last meeting attended'),
        ),
        migrations.AlterField(
            model_name='seriesmembers',
            name='paid_through',
            field=models.DateField(blank=True, null=True, verbose_name='Paid up through'),
        ),
        migrations.AlterField(
            model_name='style',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='series',
            index=models.Index(fields=['style', 'title'], name='styles_seri_style_i_1bb978_idx'),
        ),
    ]
