# Generated by Django 3.2.7 on 2021-10-06 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_alter_resource_id'),
        ('styles', '0008_auto_20211006_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='resources',
            field=models.ManyToManyField(null=True, to='resources.Resource'),
        ),
    ]
