# Generated by Django 3.2.7 on 2021-10-06 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_alter_resource_id'),
        ('styles', '0009_alter_series_resources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='resources',
            field=models.ManyToManyField(blank=True, to='resources.Resource'),
        ),
    ]
