# Generated by Django 3.0.11 on 2020-12-05 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='gmaps_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='gmaps_geolocation',
            new_name='geolocation',
        ),
    ]
